services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: irisvision
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  monitoring:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-3.11.3.linux-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped

  dashboard:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped  

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

